import type { APIRoute } from 'astro';
import { supabase } from '../../../../lib/supabase';

export const GET: APIRoute = async ({ params, request }) => {
  try {
    const { id } = params;
    if (!id) {
      return new Response(JSON.stringify({ error: 'Quiz ID required' }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    // Get quiz
    const { data: quiz, error: quizError } = await supabase
      .from('quizzes')
      .select('*')
      .eq('id', id)
      .single();

    if (quizError || !quiz) {
      return new Response(JSON.stringify({ error: 'Quiz not found' }), {
        status: 404,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    // Get questions with options
    const { data: questions, error: questionsError } = await supabase
      .from('questions')
      .select('*, question_options(*)')
      .eq('quiz_id', id)
      .order('order_index');

    if (questionsError) {
      return new Response(JSON.stringify({ error: questionsError.message }), {
        status: 500,
        headers: { 'Content-Type': 'application/json' },
      });
    }

    // Generate PDF content (simplified HTML for now)
    const htmlContent = generateQuizPDF(quiz, questions || []);

    return new Response(htmlContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="${quiz.title}.html"`,
      },
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: 'Internal server error' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
};

function generateQuizPDF(quiz: any, questions: any[]): string {
  const questionHTML = questions.map((q, index) => {
    let optionsHTML = '';
    if (q.type === 'single_choice' || q.type === 'multiple_choice') {
      optionsHTML = q.question_options
        .sort((a: any, b: any) => a.order_index - b.order_index)
        .map((opt: any, i: number) => `
          <div class="option">
            <span class="option-label">${String.fromCharCode(65 + i)}.</span>
            <span class="option-content">${opt.content}</span>
          </div>
        `).join('');
    } else if (q.type === 'true_false') {
      optionsHTML = `
        <div class="option">
          <span class="option-label">A.</span>
          <span class="option-content">正确</span>
        </div>
        <div class="option">
          <span class="option-label">B.</span>
          <span class="option-content">错误</span>
        </div>
      `;
    } else if (q.type === 'fill_blank') {
      optionsHTML = '<div class="blank-line">________________</div>';
    } else if (q.type === 'short_answer') {
      optionsHTML = '<div class="short-answer-lines">________________________________</div>';
    }

    return `
      <div class="question">
        <div class="question-header">
          <span class="question-number">${index + 1}.</span>
          <span class="question-type">[${getTypeName(q.type)}]</span>
          <span class="question-points">(${q.points}分)</span>
        </div>
        <div class="question-content">${q.content}</div>
        <div class="question-options">${optionsHTML}</div>
      </div>
    `;
  }).join('');

  return `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>${quiz.title}</title>
  <style>
    body { font-family: 'Microsoft YaHei', sans-serif; margin: 40px; line-height: 1.6; }
    .title { text-align: center; font-size: 24px; font-weight: bold; margin-bottom: 20px; }
    .description { text-align: center; color: #666; margin-bottom: 30px; }
    .question { margin-bottom: 24px; padding: 16px; border: 1px solid #ddd; border-radius: 8px; }
    .question-header { margin-bottom: 12px; }
    .question-number { font-weight: bold; }
    .question-type { color: #666; font-size: 14px; }
    .question-points { color: #999; font-size: 14px; }
    .question-content { margin-bottom: 12px; }
    .option { margin: 8px 0; padding-left: 24px; }
    .option-label { font-weight: bold; margin-right: 8px; }
    .blank-line { margin: 12px 0; padding: 8px; border-bottom: 1px solid #000; }
    .short-answer-lines { margin: 12px 0; padding: 8px; border: 1px solid #ddd; min-height: 100px; }
    .footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <div class="title">${quiz.title}</div>
  ${quiz.description ? `<div class="description">${quiz.description}</div>` : ''}
  <div class="questions">${questionHTML}</div>
  <div class="footer">Generated by iQuiz</div>
</body>
</html>
  `;
}

function getTypeName(type: string): string {
  const types: Record<string, string> = {
    single_choice: '单选题',
    multiple_choice: '多选题',
    true_false: '判断题',
    fill_blank: '填空题',
    short_answer: '简答题',
  };
  return types[type] || type;
}